name: nutriveda_mobile
description: A Flutter app for dietitians with patient management, analysis and history

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.6
  supabase: ^2.2.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  uuid: ^4.5.1
  # Image processing for food classification
  # tflite: ^1.1.2  # TODO: Uncomment when ready for production ML inference
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - food_classifier_final.h5
    - class_indices.pkl